language: c

sudo: required
dist: trusty

compiler:
  - gcc

before_install: chmod +x travis/*

script: travis/make.sh

notifications:
  email: false

addons:
  sonarcloud:
    organization: "katajakasa-github"
  apt:
    sources:
    - sourceline: 'ppa:zoogie/sdl2-snapshots'
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:george-edison55/cmake-3.x'
    - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages:
    - cmake
    - gcc-7
    - libsdl2-dev
    - libass-dev
    - ffmpeg

cache:
  directories:
    - '$HOME/.sonar/cache'
